package moe.ditto.halo.ui

data class LanguageOption(val code: String, val label: String)

private val LanguageLabels = mapOf(
    "ara" to "Arabic",
    "bul" to "Bulgarian",
    "chi" to "Chinese",
    "zho" to "Chinese",
    "cze" to "Czech",
    "ces" to "Czech",
    "dan" to "Danish",
    "dut" to "Dutch",
    "nld" to "Dutch",
    "eng" to "English",
    "est" to "Estonian",
    "fin" to "Finnish",
    "fre" to "French",
    "fra" to "French",
    "ger" to "German",
    "deu" to "German",
    "gre" to "Greek",
    "ell" to "Greek",
    "heb" to "Hebrew",
    "hin" to "Hindi",
    "hrv" to "Croatian",
    "hun" to "Hungarian",
    "ind" to "Indonesian",
    "ita" to "Italian",
    "jpn" to "Japanese",
    "kor" to "Korean",
    "lav" to "Latvian",
    "lit" to "Lithuanian",
    "may" to "Malay",
    "msa" to "Malay",
    "nor" to "Norwegian",
    "per" to "Persian",
    "fas" to "Persian",
    "pol" to "Polish",
    "por" to "Portuguese",
    "pob" to "Portuguese (BR)",
    "rum" to "Romanian",
    "ron" to "Romanian",
    "rus" to "Russian",
    "slo" to "Slovak",
    "slk" to "Slovak",
    "slv" to "Slovenian",
    "spa" to "Spanish",
    "srp" to "Serbian",
    "swe" to "Swedish",
    "tha" to "Thai",
    "tur" to "Turkish",
    "ukr" to "Ukrainian",
    "vie" to "Vietnamese",
)

fun languageLabel(code: String): String = LanguageLabels[code.trim().lowercase()] ?: code

val LanguageOptions = listOf(
    "eng", "spa", "por", "pob", "fre", "ger", "ita", "dut", "pol", "rus",
    "ukr", "swe", "nor", "dan", "fin", "cze", "slo", "slv", "hrv", "srp",
    "hun", "rum", "bul", "gre", "tur", "ara", "heb", "per", "hin", "tha",
    "vie", "ind", "may", "chi", "jpn", "kor", "est", "lav", "lit",
).map { code -> LanguageOption(code, LanguageLabels.getValue(code)) }
